version = '2'

[run]
build-tags = [
  'sudo',
  'netnstest',
  'manual'
]
tests = true

[linters]
default = 'none'
enable = [
  'bodyclose',
  'errcheck',
  'errname',
  'errorlint',
  'forcetypeassert',
  'gosec',
  'govet',
  'importas',
  'ineffassign',
  'revive',
  'staticcheck',
  'testifylint',
  'unconvert',
  'unused'
]

[linters.settings]
[linters.settings.gosec]
excludes = [
  'G306',
  'G115',
  'G601'
]

[linters.settings.govet]
disable = [
  'fieldalignment',
  'shadow',
  'unusedwrite'
]
enable-all = true

[linters.settings.govet.settings]
[linters.settings.govet.settings.printf]
funcs = ['(*go.uber.org/zap.SugaredLogger).DPanicf', '(*go.uber.org/zap.SugaredLogger).Debugf', '(*go.uber.org/zap.SugaredLogger).Infof', '(*go.uber.org/zap.SugaredLogger).Warnf', '(*go.uber.org/zap.SugaredLogger).Errorf', '(*go.uber.org/zap.SugaredLogger).Fatalf', '(*go.uber.org/zap.SugaredLogger).Panicf']

[linters.settings.revive]
[[linters.settings.revive.rules]]
name = 'atomic'

[[linters.settings.revive.rules]]
name = 'blank-imports'

[[linters.settings.revive.rules]]
name = 'context-keys-type'

[[linters.settings.revive.rules]]
name = 'range'

[[linters.settings.revive.rules]]
name = 'receiver-naming'

[[linters.settings.revive.rules]]
name = 'unreachable-code'

[linters.settings.staticcheck]
checks = [
  'all',
  '-QF*',
  '-ST1000',
  '-ST1003',
  '-ST1023',
  'SA9003',
  'ST1016'
]

[linters.settings.testifylint]
enable-all = true
disable-all = false
disable = [
  'require-error'
]

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  '.*goaviatrix/client_mock\.go',
  'third_party$',
  'builtin$',
  'examples$'
]

[[linters.exclusions.rules]]
linters = [
  'funlen'
]
source = '^func Test'

[[linters.exclusions.rules]]
linters = [
  'testifylint'
]
text = 'require-error: for error assertions use require'

[issues]
fix = true

[formatters]
enable = [
  'gofumpt',
  'goimports'
]

[formatters.settings]
[formatters.settings.goimports]
local-prefixes = [
  'aviatrix.com'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  '.*goaviatrix/client_mock\.go',
  'third_party$',
  'builtin$',
  'examples$'
]
