ARM_APPLICATION_ID=$(terraform output ARM_APPLICATION_ID)
ARM_APPLICATION_KEY=$(terraform output ARM_APPLICATION_KEY)
ARM_DIRECTORY_ID=$(terraform output ARM_DIRECTORY_ID)
ARM_GW_SIZE=$(terraform output ARM_GW_SIZE)
ARM_REGION=$(terraform output ARM_REGION)
ARM_REGION2=$(terraform output ARM_REGION2)
ARM_SUBNET=$(terraform output ARM_SUBNET)
ARM_SUBSCRIPTION_ID=$(terraform output ARM_SUBSCRIPTION_ID)
ARM_VNET_ID=$(terraform output ARM_VNET_ID)
ARM_VNET_ID2=$(terraform output ARM_VNET_ID2)
AVIATRIX_CONTROLLER_IP=$(terraform output AVIATRIX_CONTROLLER_IP)
AVIATRIX_PASSWORD=$(terraform output AVIATRIX_PASSWORD)
AVIATRIX_USERNAME=$(terraform output AVIATRIX_USERNAME)
AWS_ACCESS_KEY=$(terraform output AWS_ACCESS_KEY)
AWS_ACCOUNT_NUMBER=$(terraform output AWS_ACCOUNT_NUMBER)
AWS_BGP_VGW_ID=$(terraform output AWS_BGP_VGW_ID)
AWS_REGION=$(terraform output AWS_REGION)
AWS_REGION2=$(terraform output AWS_REGION2)
AWS_SECRET_KEY=$(terraform output AWS_SECRET_KEY)
AWS_SUBNET=$(terraform output AWS_SUBNET)
AWS_SUBNET2=$(terraform output AWS_SUBNET2)
AWS_VPC_ID=$(terraform output AWS_VPC_ID)
AWS_VPC_ID2=$(terraform output AWS_VPC_ID2)
GCP_CREDENTIALS_FILEPATH=$(terraform output GCP_CREDENTIALS_FILEPATH)
GCP_ID=$(terraform output GCP_ID)
GCP_SUBNET=$(terraform output GCP_SUBNET)
GCP_VPC_ID=$(terraform output GCP_VPC_ID)
GCP_ZONE=$(terraform output GCP_ZONE)
IDP_METADATA=$(terraform output IDP_METADATA)
IDP_METADATA_TYPE=$(terraform output IDP_METADATA_TYPE)
OCI_API_KEY_FILEPATH=$(terraform output OCI_API_KEY_FILEPATH)
OCI_COMPARTMENT_ID=$(terraform output OCI_COMPARTMENT_ID)
OCI_REGION=$(terraform output OCI_REGION)
OCI_SUBNET=$(terraform output OCI_SUBNET)
OCI_TENANCY_ID=$(terraform output OCI_TENANCY_ID)
OCI_USER_ID=$(terraform output OCI_USER_ID)
OCI_VPC_ID=$(terraform output OCI_VPC_ID)
controller_private_ip=$(terraform output controller_private_ip)

SKIP_DATA_ACCOUNT="no"
SKIP_DATA_CALLER_IDENTITY="no"
SKIP_DATA_GATEWAY="no"
SKIP_ACCOUNT="no"
SKIP_ACCOUNT_AWS="no"
SKIP_ACCOUNT_ARM="no"
SKIP_ACCOUNT_GCP="no"
SKIP_ACCOUNT_OCI="no"
SKIP_ACCOUNT_USER="no"
SKIP_ARM_PEER="no"
SKIP_AWS_PEER="no"
SKIP_AWS_TGW="no"
SKIP_AWS_TGW_VPC_ATTACHMENT="no"
SKIP_AWS_TGW_VPN_CONN="no"
SKIP_CONTROLLER_CONFIG="no"
SKIP_FIREWALL="no"
SKIP_FIREWALL_TAG="no"
SKIP_FQDN="no"
SKIP_GATEWAY="no"
SKIP_GATEWAY_AWS="no"
SKIP_GATEWAY_GCP="no"
SKIP_GATEWAY_ARM="no"
SKIP_GATEWAY_OCI="no"
SKIP_SAML_ENDPOINT="no"
SKIP_S2C="no"
SKIP_SPOKE="no"
SKIP_SPOKE_ARM="no"
SKIP_SPOKE_AWS="no"
SKIP_SPOKE_GCP="no"
SKIP_SPOKE_GATEWAY="no"
SKIP_SPOKE_GATEWAY_ARM="no"
SKIP_SPOKE_GATEWAY_AWS="no"
SKIP_SPOKE_GATEWAY_GCP="no"
SKIP_SPOKE_GATEWAY_OCI="no"
SKIP_TRANSIT="no"
SKIP_TRANSIT_AWS="no"
SKIP_TRANSIT_ARM="no"
SKIP_TRANSIT_GATEWAY="no"
SKIP_TRANSIT_GATEWAY_AWS="no"
SKIP_TRANSIT_GATEWAY_ARM="no"
SKIP_TRANSIT_GATEWAY_GCP="no"
SKIP_TRANSIT_GATEWAY_OCI="no"
SKIP_TRANSIT_GATEWAY_PEERING="no"
SKIP_TRANS_PEER="no"
SKIP_TUNNEL="no"
SKIP_VPC="no"
SKIP_VGW_CONN="no"
SKIP_VPN_PROFILE="no"
SKIP_VPN_USER="no"
SKIP_VPN_USER_ACCELERATOR="no"

export ARM_APPLICATION_ID
export ARM_APPLICATION_KEY
export ARM_DIRECTORY_ID
export ARM_GW_SIZE
export ARM_REGION
export ARM_REGION2
export ARM_SUBNET
export ARM_SUBSCRIPTION_ID
export ARM_VNET_ID
export ARM_VNET_ID2
export AVIATRIX_CONTROLLER_IP
export AVIATRIX_PASSWORD
export AVIATRIX_USERNAME
export AWS_ACCESS_KEY
export AWS_ACCOUNT_NUMBER
export AWS_BGP_VGW_ID
export AWS_REGION
export AWS_REGION2
export AWS_SECRET_KEY
export AWS_SUBNET
export AWS_SUBNET2
export AWS_VPC_ID
export AWS_VPC_ID2
export GCP_CREDENTIALS_FILEPATH
export GCP_ID
export GCP_SUBNET
export GCP_VPC_ID
export GCP_ZONE
export IDP_METADATA
export IDP_METADATA_TYPE
export OCI_API_KEY_FILEPATH
export OCI_COMPARTMENT_ID
export OCI_REGION
export OCI_SUBNET
export OCI_TENANCY_ID
export OCI_USER_ID
export OCI_VPC_ID
export controller_private_ip

export SKIP_DATA_ACCOUNT
export SKIP_DATA_CALLER_IDENTITY
export SKIP_DATA_GATEWAY
export SKIP_ACCOUNT
export SKIP_ACCOUNT_AWS
export SKIP_ACCOUNT_ARM
export SKIP_ACCOUNT_GCP
export SKIP_ACCOUNT_OCI
export SKIP_ACCOUNT_USER
export SKIP_ARM_PEER
export SKIP_AWS_PEER
export SKIP_AWS_TGW
export SKIP_AWS_TGW_VPC_ATTACHMENT
export SKIP_AWS_TGW_VPN_CONN
export SKIP_CONTROLLER_CONFIG
export SKIP_FIREWALL
export SKIP_FIREWALL_TAG
export SKIP_FQDN
export SKIP_GATEWAY
export SKIP_GATEWAY_AWS
export SKIP_GATEWAY_GCP
export SKIP_GATEWAY_ARM
export SKIP_GATEWAY_OCI
export SKIP_SAML_ENDPOINT
export SKIP_S2C
export SKIP_SPOKE
export SKIP_SPOKE_ARM
export SKIP_SPOKE_AWS
export SKIP_SPOKE_GCP
export SKIP_SPOKE_GATEWAY
export SKIP_SPOKE_GATEWAY_ARM
export SKIP_SPOKE_GATEWAY_AWS
export SKIP_SPOKE_GATEWAY_GCP
export SKIP_SPOKE_GATEWAY_OCI
export SKIP_TRANSIT
export SKIP_TRANSIT_AWS
export SKIP_TRANSIT_ARM
export SKIP_TRANSIT_GATEWAY
export SKIP_TRANSIT_GATEWAY_AWS
export SKIP_TRANSIT_GATEWAY_ARM
export SKIP_TRANSIT_GATEWAY_GCP
export SKIP_TRANSIT_GATEWAY_OCI
export SKIP_TRANSIT_GATEWAY_PEERING
export SKIP_TRANS_PEER
export SKIP_TUNNEL
export SKIP_VPC
export SKIP_VGW_CONN
export SKIP_VPN_PROFILE
export SKIP_VPN_USER
export SKIP_VPN_USER_ACCELERATOR
