name: go

on:
  push:
    branches:
      - rc-*

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.25
      id: go
    
    - name: Generate go.mod
      run: |
        go mod init aviatrix.com/terraform-provider-aviatrix
        go mod tidy

    - name: Commit changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add go.mod go.sum
        git commit -m "Update go.mod and go.sum"
        git push
