name: go

on:
  push:
    branches:
      - master
      - rc-*

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get TF Release Token
      id: get_tf_release_token
      uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
      with:
        organization: AviatrixSystems
        application_id: ${{ secrets.AVIATRIXDEV_SYSTEMS_TRIGGER_APP_ID }}
        application_private_key: ${{ secrets.AVIATRIXDEV_SYSTEMS_TRIGGER_PRIVATE_KEY }}
    
    - name: Config git url AviatrixPlatform
      env:
        AVIATRIX_SYSTEMS_TOKEN: ${{ steps.get_workflow_token_aviatrixsystems.outputs.token }}
      run: |
        git config --global url.https://git:${AVIATRIX_SYSTEMS_TOKEN}@github.com/AviatrixSystems/.insteadOf https://github.com/AviatrixSystems

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.25
      id: go
    
    - name: Generate go.mod
      run: |
        go mod init aviatrix.com/terraform-provider-aviatrix
        go mod tidy

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ steps.get_tf_release_token.outputs.token }}
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add go.mod go.sum
        git commit -m "Update go.mod and go.sum"
        git push
