name: Export provider public key
on: {workflow_dispatch: {}}
permissions:
  contents: read
jobs:
  export-pubkey:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Show fingerprint (not secret)
        run: |
          echo "Fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
      - name: Export public key (ASCII-armored)
        run: |
          gpg --armor --export "${{ steps.import_gpg.outputs.fingerprint }}" > provider-signing-public-key.asc
          {
            echo '### Provider public key (ASCII-armored)'
            echo
            echo '```'
            cat provider-signing-public-key.asc
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: provider-signing-public-key
          path: provider-signing-public-key.asc
          retention-days: 1
